Upgrade Ruby to 2.1.2

diff --git a/packages/ruby/packaging b/packages/ruby/packaging
--- a/packages/ruby/packaging
+++ b/packages/ruby/packaging
@@ -5,9 +5,18 @@ set -u # report the usage of uninitialized variables
 CPUS=`grep -c ^processor /proc/cpuinfo`
 
 # We grab the latest versions that are in the directory
-RUBY_VERSION=`ls -r ruby/ruby-*.tar.gz | sed 's/ruby\/ruby-\(.*\)\.tar\.gz/\1/' | head -1`
-RUBYGEMS_VERSION=`ls -r ruby/rubygems-*.tgz | sed 's/ruby\/rubygems-\(.*\)\.tgz/\1/' | head -1`
-BUNDLER_VERSION=`ls -r ruby/bundler-*.gem | sed 's/ruby\/bundler-\(.*\)\.gem/\1/' | head -1`
+LIBYAML_VERSION=`ls -r ruby/yaml-* | sed 's/ruby\/yaml-\(.*\)\.tar\.gz/\1/' | head -1`
+RUBY_VERSION=`ls -r ruby/ruby-* | sed 's/ruby\/ruby-\(.*\)\.tar\.gz/\1/' | head -1`
+RUBYGEMS_VERSION=`ls -r ruby/rubygems-* | sed 's/ruby\/rubygems-\(.*\)\.tgz/\1/' | head -1`
+BUNDLER_VERSION=`ls -r ruby/bundler-* | sed 's/ruby\/bundler-\(.*\)\.gem/\1/' | head -1`
+
+# Extract Yaml package
+echo "Extracting Yaml ${LIBYAML_VERSION}..."
+tar xzvf ${BOSH_COMPILE_TARGET}/ruby/yaml-${LIBYAML_VERSION}.tar.gz
+if [[ $? != 0 ]] ; then
+  echo "Failed extracting Yaml ${LIBYAML_VERSION}"
+  exit 1
+fi
 
 # Extract Ruby package
 echo "Extracting Ruby ${RUBY_VERSION}..."
@@ -25,10 +34,18 @@ if [[ $? != 0 ]] ; then
   exit 1
 fi
 
+# Build Yaml package
+echo "Building Yaml ${LIBYAML_VERSION}..."
+cd ${BOSH_COMPILE_TARGET}/yaml-${LIBYAML_VERSION}
+./configure --prefix=${BOSH_INSTALL_TARGET}
+make -j${CPUS}
+make install
+ldconfig
+
 # Build Ruby package
 echo "Building Ruby ${RUBY_VERSION}..."
 cd ${BOSH_COMPILE_TARGET}/ruby-${RUBY_VERSION}
-./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc
+./configure --prefix=${BOSH_INSTALL_TARGET} --disable-install-doc --with-opt-dir=/var/vcap/packages/ruby/lib
 make -j${CPUS}
 make install
 
@@ -36,7 +53,12 @@ make install
 echo "Installing Rubygems ${RUBYGEMS_VERSION}..."
 cd ${BOSH_COMPILE_TARGET}/rubygems-${RUBYGEMS_VERSION}
 ${BOSH_INSTALL_TARGET}/bin/ruby setup.rb
+if [[ $? != 0 ]] ; then
+  echo "Failed installing Rubygems ${RUBYGEMS_VERSION}"
+  exit 1
+fi
 
 # Install Bundler package
 echo "Installing Bundler ${BUNDLER_VERSION}..."
-${BOSH_INSTALL_TARGET}/bin/gem install ${BOSH_COMPILE_TARGET}/ruby/bundler-${BUNDLER_VERSION}.gem --local --no-ri --no-rdoc
+${BOSH_INSTALL_TARGET}/bin/gem install ${BOSH_COMPILE_TARGET}/ruby/bundler-${BUNDLER_VERSION}.gem --no-ri --no-rdoc
+
